import re, csv
import sys
import json
import time
import string
import requests
import unicodedata
import urllib3
import numpy as np
import pandas as pd
import itertools

from bs4 import BeautifulSoup

game_id_list = range(400974437, 400975976, 1)

game_num = 0
for gameid in range(400974437, 400975977, 1):
    game_array = np.empty((300, 30), 'object')
    print('Getting gameid=%s' % gameid)
    r = requests.get('http://www.espn.com/nba/game?gameId=%s' % gameid)
    // r2 = requests.get('http://www.espn.com/college-football/game?gameId=%s' % gameid)
    soup = BeautifulSoup(r.text, 'html.parser')

    dataPlay = soup.find_all("data-plays")
    dataPlay = gameFlow.find_all('data-plays')

<div id="gameFlow-graph"
data-plays="[{&quot;period&quot;:1,&quot;seconds&quot;:0,&quot;homeScore&quot;:0,&quot;awayScore&quot;:0,&quot;text&quot;:&quot;&quot;,&quot;clock&quot;:&quot;12:00&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:20,&quot;homeScore&quot;:1,&quot;awayScore&quot;:0,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;4009757859&quot;,&quot;text&quot;:&quot;Cristiano Felicio makes free throw 1 of 2&quot;,&quot;clock&quot;:&quot;11:40&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:20,&quot;homeScore&quot;:2,&quot;awayScore&quot;:0,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;40097578510&quot;,&quot;text&quot;:&quot;Cristiano Felicio makes free throw 2 of 2&quot;,&quot;clock&quot;:&quot;11:40&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:39,&quot;homeScore&quot;:2,&quot;awayScore&quot;:2,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578511&quot;,&quot;text&quot;:&quot;Jeff Green makes two point shot&quot;,&quot;clock&quot;:&quot;11:21&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:69,&quot;homeScore&quot;:2,&quot;awayScore&quot;:4,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578514&quot;,&quot;text&quot;:&quot;LeBron James makes driving layup&quot;,&quot;clock&quot;:&quot;10:51&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:88,&quot;homeScore&quot;:5,&quot;awayScore&quot;:4,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;40097578519&quot;,&quot;text&quot;:&quot;Cameron Payne makes 27-foot three point jumper (Cristiano Felicio assists)&quot;,&quot;clock&quot;:&quot;10:32&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:105,&quot;homeScore&quot;:5,&quot;awayScore&quot;:7,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578521&quot;,&quot;text&quot;:&quot;Jose Calderon makes three point jumper (George Hill assists)&quot;,&quot;clock&quot;:&quot;10:15&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:129,&quot;homeScore&quot;:5,&quot;awayScore&quot;:8,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578527&quot;,&quot;text&quot;:&quot;Jeff Green makes technical free throw&quot;,&quot;clock&quot;:&quot;9:51&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:140,&quot;homeScore&quot;:5,&quot;awayScore&quot;:10,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578528&quot;,&quot;text&quot;:&quot;Ante Zizic makes layup (LeBron James assists)&quot;,&quot;clock&quot;:&quot;9:40&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:162,&quot;homeScore&quot;:7,&quot;awayScore&quot;:10,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;40097578530&quot;,&quot;text&quot;:&quot;Cristiano Felicio makes 19-foot jumper (Cameron Payne assists)&quot;,&quot;clock&quot;:&quot;9:18&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:174,&quot;homeScore&quot;:7,&quot;awayScore&quot;:12,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578532&quot;,&quot;text&quot;:&quot;LeBron James makes driving layup&quot;,&quot;clock&quot;:&quot;9:06&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:210,&quot;homeScore&quot;:9,&quot;awayScore&quot;:12,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;40097578541&quot;,&quot;text&quot;:&quot;Justin Holiday makes layup (Denzel Valentine assists)&quot;,&quot;clock&quot;:&quot;8:30&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:210,&quot;homeScore&quot;:10,&quot;awayScore&quot;:12,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;40097578545&quot;,&quot;text&quot;:&quot;Justin Holiday makes free throw 1 of 1&quot;,&quot;clock&quot;:&quot;8:30&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:224,&quot;homeScore&quot;:10,&quot;awayScore&quot;:14,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578546&quot;,&quot;text&quot;:&quot;LeBron James makes alley oop dunk shot (Jose Calderon assists)&quot;,&quot;clock&quot;:&quot;8:16&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:232,&quot;homeScore&quot;:13,&quot;awayScore&quot;:14,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;40097578548&quot;,&quot;text&quot;:&quot;Paul Zipser makes 25-foot three point jumper (Cameron Payne assists)&quot;,&quot;clock&quot;:&quot;8:08&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:252,&quot;homeScore&quot;:13,&quot;awayScore&quot;:17,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578550&quot;,&quot;text&quot;:&quot;Jeff Green makes 23-foot three point jumper (Jose Calderon assists)&quot;,&quot;clock&quot;:&quot;7:48&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:268,&quot;homeScore&quot;:15,&quot;awayScore&quot;:17,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;40097578552&quot;,&quot;text&quot;:&quot;Denzel Valentine makes two point shot (Justin Holiday assists)&quot;,&quot;clock&quot;:&quot;7:32&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:284,&quot;homeScore&quot;:15,&quot;awayScore&quot;:19,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578554&quot;,&quot;text&quot;:&quot;Ante Zizic makes dunk (LeBron James assists)&quot;,&quot;clock&quot;:&quot;7:16&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:295,&quot;homeScore&quot;:17,&quot;awayScore&quot;:19,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;40097578558&quot;,&quot;text&quot;:&quot;Justin Holiday makes tip shot&quot;,&quot;clock&quot;:&quot;7:05&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:313,&quot;homeScore&quot;:17,&quot;awayScore&quot;:22,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578560&quot;,&quot;text&quot;:&quot;LeBron James makes 23-foot three point jumper (Jose Calderon assists)&quot;,&quot;clock&quot;:&quot;6:47&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:358,&quot;homeScore&quot;:17,&quot;awayScore&quot;:24,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578568&quot;,&quot;text&quot;:&quot;Ante Zizic makes two point shot&quot;,&quot;clock&quot;:&quot;6:02&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:379,&quot;homeScore&quot;:20,&quot;awayScore&quot;:24,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;40097578569&quot;,&quot;text&quot;:&quot;Cameron Payne makes 24-foot step back jumpshot (Cristiano Felicio assists)&quot;,&quot;clock&quot;:&quot;5:41&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:407,&quot;homeScore&quot;:23,&quot;awayScore&quot;:24,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;40097578574&quot;,&quot;text&quot;:&quot;Denzel Valentine makes 26-foot three point jumper (Justin Holiday assists)&quot;,&quot;clock&quot;:&quot;5:13&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:435,&quot;homeScore&quot;:23,&quot;awayScore&quot;:26,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;40097578587&quot;,&quot;text&quot;:&quot;Jeff Green makes dunk (LeBron James assists)&quot;,&quot;clock&quot;:&quot;4:45&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:501,&quot;homeScore&quot;:23,&quot;awayScore&quot;:29,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785103&quot;,&quot;text&quot;:&quot;Jeff Green makes 26-foot three point jumper (London Perrantes assists)&quot;,&quot;clock&quot;:&quot;3:39&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:521,&quot;homeScore&quot;:25,&quot;awayScore&quot;:29,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785105&quot;,&quot;text&quot;:&quot;Bobby Portis makes 12-foot two point shot&quot;,&quot;clock&quot;:&quot;3:19&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:545,&quot;homeScore&quot;:25,&quot;awayScore&quot;:31,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785106&quot;,&quot;text&quot;:&quot;Jeff Green makes driving dunk (London Perrantes assists)&quot;,&quot;clock&quot;:&quot;2:55&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:549,&quot;homeScore&quot;:26,&quot;awayScore&quot;:31,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785119&quot;,&quot;text&quot;:&quot;Jerian Grant makes free throw 2 of 2&quot;,&quot;clock&quot;:&quot;2:51&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:585,&quot;homeScore&quot;:28,&quot;awayScore&quot;:31,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785121&quot;,&quot;text&quot;:&quot;Bobby Portis makes two point shot&quot;,&quot;clock&quot;:&quot;2:15&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:640,&quot;homeScore&quot;:29,&quot;awayScore&quot;:31,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785138&quot;,&quot;text&quot;:&quot;David Nwaba makes free throw 2 of 2&quot;,&quot;clock&quot;:&quot;1:20&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:671,&quot;homeScore&quot;:31,&quot;awayScore&quot;:31,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785145&quot;,&quot;text&quot;:&quot;David Nwaba makes tip shot&quot;,&quot;clock&quot;:&quot;49.8&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:679,&quot;homeScore&quot;:31,&quot;awayScore&quot;:32,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785148&quot;,&quot;text&quot;:&quot;Jeff Green makes free throw 1 of 2&quot;,&quot;clock&quot;:&quot;41.3&quot;}," \
           "{&quot;period&quot;:1,&quot;seconds&quot;:720,&quot;homeScore&quot;:31,&quot;awayScore&quot;:32,&quot;teamId&quot;:0,&quot;id&quot;:&quot;400975785160&quot;,&quot;text&quot;:&quot;End of the 1st Quarter&quot;,&quot;clock&quot;:&quot;0.0&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:738,&quot;homeScore&quot;:31,&quot;awayScore&quot;:34,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785162&quot;,&quot;text&quot;:&quot;Jeff Green makes dunk (Jose Calderon assists)&quot;,&quot;clock&quot;:&quot;11:42&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:772,&quot;homeScore&quot;:31,&quot;awayScore&quot;:36,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785166&quot;,&quot;text&quot;:&quot;John Holland makes dunk (Jeff Green assists)&quot;,&quot;clock&quot;:&quot;11:08&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:799,&quot;homeScore&quot;:31,&quot;awayScore&quot;:38,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785174&quot;,&quot;text&quot;:&quot;Jose Calderon makes layup&quot;,&quot;clock&quot;:&quot;10:41&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:817,&quot;homeScore&quot;:31,&quot;awayScore&quot;:39,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785181&quot;,&quot;text&quot;:&quot;Jose Calderon makes technical free throw&quot;,&quot;clock&quot;:&quot;10:23&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:859,&quot;homeScore&quot;:31,&quot;awayScore&quot;:42,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785187&quot;,&quot;text&quot;:&quot;Jordan Clarkson makes 25-foot three point jumper (LeBron James assists)&quot;,&quot;clock&quot;:&quot;9:41&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:885,&quot;homeScore&quot;:31,&quot;awayScore&quot;:45,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785194&quot;,&quot;text&quot;:&quot;Jordan Clarkson makes three point jumper (LeBron James assists)&quot;,&quot;clock&quot;:&quot;9:15&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:918,&quot;homeScore&quot;:31,&quot;awayScore&quot;:48,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785200&quot;,&quot;text&quot;:&quot;Jordan Clarkson makes 24-foot three point jumper (Jose Calderon assists)&quot;,&quot;clock&quot;:&quot;8:42&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:939,&quot;homeScore&quot;:33,&quot;awayScore&quot;:48,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785207&quot;,&quot;text&quot;:&quot;David Nwaba makes layup (Cameron Payne assists)&quot;,&quot;clock&quot;:&quot;8:21&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:966,&quot;homeScore&quot;:36,&quot;awayScore&quot;:48,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785211&quot;,&quot;text&quot;:&quot;Denzel Valentine makes 26-foot three point jumper (Cameron Payne assists)&quot;,&quot;clock&quot;:&quot;7:54&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1034,&quot;homeScore&quot;:36,&quot;awayScore&quot;:50,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785224&quot;,&quot;text&quot;:&quot;LeBron James makes driving layup&quot;,&quot;clock&quot;:&quot;6:46&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1034,&quot;homeScore&quot;:36,&quot;awayScore&quot;:51,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785229&quot;,&quot;text&quot;:&quot;LeBron James makes free throw 1 of 1&quot;,&quot;clock&quot;:&quot;6:46&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1043,&quot;homeScore&quot;:39,&quot;awayScore&quot;:51,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785230&quot;,&quot;text&quot;:&quot;Denzel Valentine makes 25-foot three point jumper (Paul Zipser assists)&quot;,&quot;clock&quot;:&quot;6:37&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1063,&quot;homeScore&quot;:39,&quot;awayScore&quot;:53,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785233&quot;,&quot;text&quot;:&quot;LeBron James makes 16-foot jumper&quot;,&quot;clock&quot;:&quot;6:17&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1087,&quot;homeScore&quot;:41,&quot;awayScore&quot;:53,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785234&quot;,&quot;text&quot;:&quot;Cameron Payne makes 10-foot jumper (Denzel Valentine assists)&quot;,&quot;clock&quot;:&quot;5:53&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1125,&quot;homeScore&quot;:41,&quot;awayScore&quot;:55,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785238&quot;,&quot;text&quot;:&quot;Jordan Clarkson makes 22-foot jumper&quot;,&quot;clock&quot;:&quot;5:15&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1136,&quot;homeScore&quot;:44,&quot;awayScore&quot;:55,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785239&quot;,&quot;text&quot;:&quot;Paul Zipser makes 25-foot three point jumper (Cameron Payne assists)&quot;,&quot;clock&quot;:&quot;5:04&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1181,&quot;homeScore&quot;:46,&quot;awayScore&quot;:55,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785253&quot;,&quot;text&quot;:&quot;Antonio Blakeney makes layup (Cameron Payne assists)&quot;,&quot;clock&quot;:&quot;4:19&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1224,&quot;homeScore&quot;:46,&quot;awayScore&quot;:56,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785263&quot;,&quot;text&quot;:&quot;Jordan Clarkson makes free throw 1 of 2&quot;,&quot;clock&quot;:&quot;3:36&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1224,&quot;homeScore&quot;:46,&quot;awayScore&quot;:57,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785264&quot;,&quot;text&quot;:&quot;Jordan Clarkson makes free throw 2 of 2&quot;,&quot;clock&quot;:&quot;3:36&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1247,&quot;homeScore&quot;:46,&quot;awayScore&quot;:59,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785266&quot;,&quot;text&quot;:&quot;LeBron James makes 21-foot pullup jump shot&quot;,&quot;clock&quot;:&quot;3:13&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1270,&quot;homeScore&quot;:48,&quot;awayScore&quot;:59,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785267&quot;,&quot;text&quot;:&quot;Cristiano Felicio makes 5-foot hook shot (Denzel Valentine assists)&quot;,&quot;clock&quot;:&quot;2:50&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1302,&quot;homeScore&quot;:50,&quot;awayScore&quot;:59,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785273&quot;,&quot;text&quot;:&quot;Bobby Portis makes jumper&quot;,&quot;clock&quot;:&quot;2:18&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1321,&quot;homeScore&quot;:50,&quot;awayScore&quot;:61,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785277&quot;,&quot;text&quot;:&quot;Ante Zizic makes alley oop layup (Jose Calderon assists)&quot;,&quot;clock&quot;:&quot;1:59&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1347,&quot;homeScore&quot;:50,&quot;awayScore&quot;:63,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785281&quot;,&quot;text&quot;:&quot;LeBron James makes two point shot&quot;,&quot;clock&quot;:&quot;1:33&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1382,&quot;homeScore&quot;:52,&quot;awayScore&quot;:63,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785290&quot;,&quot;text&quot;:&quot;Antonio Blakeney makes dunk&quot;,&quot;clock&quot;:&quot;58.2&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1393,&quot;homeScore&quot;:52,&quot;awayScore&quot;:66,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785291&quot;,&quot;text&quot;:&quot;George Hill makes 26-foot three point jumper (LeBron James assists)&quot;,&quot;clock&quot;:&quot;47.8&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1409,&quot;homeScore&quot;:52,&quot;awayScore&quot;:69,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785295&quot;,&quot;text&quot;:&quot;LeBron James makes three point jumper&quot;,&quot;clock&quot;:&quot;31.8&quot;}," \
           "{&quot;period&quot;:2,&quot;seconds&quot;:1440,&quot;homeScore&quot;:52,&quot;awayScore&quot;:69,&quot;teamId&quot;:0,&quot;id&quot;:&quot;400975785300&quot;,&quot;text&quot;:&quot;End of the 2nd Quarter&quot;,&quot;clock&quot;:&quot;0.0&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1502,&quot;homeScore&quot;:55,&quot;awayScore&quot;:69,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785318&quot;,&quot;text&quot;:&quot;Denzel Valentine makes 26-foot step back jumpshot&quot;,&quot;clock&quot;:&quot;10:58&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1531,&quot;homeScore&quot;:58,&quot;awayScore&quot;:69,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785324&quot;,&quot;text&quot;:&quot;Denzel Valentine makes 26-foot three point jumper (Cameron Payne assists)&quot;,&quot;clock&quot;:&quot;10:29&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1545,&quot;homeScore&quot;:58,&quot;awayScore&quot;:71,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785328&quot;,&quot;text&quot;:&quot;George Hill makes layup (LeBron James assists)&quot;,&quot;clock&quot;:&quot;10:15&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1562,&quot;homeScore&quot;:60,&quot;awayScore&quot;:71,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785330&quot;,&quot;text&quot;:&quot;Paul Zipser makes two point shot (Denzel Valentine assists)&quot;,&quot;clock&quot;:&quot;9:58&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1574,&quot;homeScore&quot;:60,&quot;awayScore&quot;:73,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785332&quot;,&quot;text&quot;:&quot;Ante Zizic makes dunk (LeBron James assists)&quot;,&quot;clock&quot;:&quot;9:46&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1636,&quot;homeScore&quot;:63,&quot;awayScore&quot;:73,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785343&quot;,&quot;text&quot;:&quot;Denzel Valentine makes 24-foot three pointer&quot;,&quot;clock&quot;:&quot;8:44&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1666,&quot;homeScore&quot;:65,&quot;awayScore&quot;:73,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785349&quot;,&quot;text&quot;:&quot;Cristiano Felicio makes layup (Cameron Payne assists)&quot;,&quot;clock&quot;:&quot;8:14&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1761,&quot;homeScore&quot;:67,&quot;awayScore&quot;:73,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785361&quot;,&quot;text&quot;:&quot;Cameron Payne makes dunk (Justin Holiday assists)&quot;,&quot;clock&quot;:&quot;6:39&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1785,&quot;homeScore&quot;:67,&quot;awayScore&quot;:75,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785363&quot;,&quot;text&quot;:&quot;Jordan Clarkson makes two point shot (LeBron James assists)&quot;,&quot;clock&quot;:&quot;6:15&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1844,&quot;homeScore&quot;:67,&quot;awayScore&quot;:77,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785375&quot;,&quot;text&quot;:&quot;LeBron James makes layup&quot;,&quot;clock&quot;:&quot;5:16&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1884,&quot;homeScore&quot;:67,&quot;awayScore&quot;:78,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785394&quot;,&quot;text&quot;:&quot;Jeff Green makes free throw 2 of 2&quot;,&quot;clock&quot;:&quot;4:36&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1904,&quot;homeScore&quot;:69,&quot;awayScore&quot;:78,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785399&quot;,&quot;text&quot;:&quot;Denzel Valentine makes 8-foot two point shot&quot;,&quot;clock&quot;:&quot;4:16&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:1938,&quot;homeScore&quot;:72,&quot;awayScore&quot;:78,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785404&quot;,&quot;text&quot;:&quot;Bobby Portis makes 23-foot three point jumper (Jerian Grant assists)&quot;,&quot;clock&quot;:&quot;3:42&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:2000,&quot;homeScore&quot;:72,&quot;awayScore&quot;:80,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785410&quot;,&quot;text&quot;:&quot;Jeff Green makes layup (LeBron James assists)&quot;,&quot;clock&quot;:&quot;2:40&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:2018,&quot;homeScore&quot;:75,&quot;awayScore&quot;:80,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785412&quot;,&quot;text&quot;:&quot;Denzel Valentine makes 26-foot three point jumper (Antonio Blakeney assists)&quot;,&quot;clock&quot;:&quot;2:22&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:2059,&quot;homeScore&quot;:77,&quot;awayScore&quot;:80,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785418&quot;,&quot;text&quot;:&quot;Bobby Portis makes two point shot&quot;,&quot;clock&quot;:&quot;1:41&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:2084,&quot;homeScore&quot;:77,&quot;awayScore&quot;:83,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785422&quot;,&quot;text&quot;:&quot;Jose Calderon makes 23-foot three point jumper (JR Smith assists)&quot;,&quot;clock&quot;:&quot;1:16&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:2097,&quot;homeScore&quot;:78,&quot;awayScore&quot;:83,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785429&quot;,&quot;text&quot;:&quot;Jerian Grant makes free throw 2 of 3&quot;,&quot;clock&quot;:&quot;1:03&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:2097,&quot;homeScore&quot;:79,&quot;awayScore&quot;:83,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785430&quot;,&quot;text&quot;:&quot;Jerian Grant makes free throw 3 of 3&quot;,&quot;clock&quot;:&quot;1:03&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:2113,&quot;homeScore&quot;:79,&quot;awayScore&quot;:85,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785431&quot;,&quot;text&quot;:&quot;LeBron James makes driving layup&quot;,&quot;clock&quot;:&quot;47.2&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:2130,&quot;homeScore&quot;:81,&quot;awayScore&quot;:85,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785432&quot;,&quot;text&quot;:&quot;Denzel Valentine makes jumper (Antonio Blakeney assists)&quot;,&quot;clock&quot;:&quot;30.3&quot;}," \
           "{&quot;period&quot;:3,&quot;seconds&quot;:2160,&quot;homeScore&quot;:81,&quot;awayScore&quot;:85,&quot;teamId&quot;:0,&quot;id&quot;:&quot;400975785438&quot;,&quot;text&quot;:&quot;End of the 3rd Quarter&quot;,&quot;clock&quot;:&quot;0.0&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2193,&quot;homeScore&quot;:81,&quot;awayScore&quot;:88,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785445&quot;,&quot;text&quot;:&quot;John Holland makes 24-foot three point jumper (George Hill assists)&quot;,&quot;clock&quot;:&quot;11:27&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2218,&quot;homeScore&quot;:82,&quot;awayScore&quot;:88,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785451&quot;,&quot;text&quot;:&quot;Antonio Blakeney makes free throw 2 of 2&quot;,&quot;clock&quot;:&quot;11:02&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2241,&quot;homeScore&quot;:84,&quot;awayScore&quot;:88,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785454&quot;,&quot;text&quot;:&quot;Bobby Portis makes dunk (David Nwaba assists)&quot;,&quot;clock&quot;:&quot;10:39&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2283,&quot;homeScore&quot;:84,&quot;awayScore&quot;:89,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785464&quot;,&quot;text&quot;:&quot;JR Smith makes free throw 1 of 2&quot;,&quot;clock&quot;:&quot;9:57&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2283,&quot;homeScore&quot;:84,&quot;awayScore&quot;:90,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785467&quot;,&quot;text&quot;:&quot;JR Smith makes free throw 2 of 2&quot;,&quot;clock&quot;:&quot;9:57&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2326,&quot;homeScore&quot;:84,&quot;awayScore&quot;:93,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785477&quot;,&quot;text&quot;:&quot;JR Smith makes 24-foot three point jumper&quot;,&quot;clock&quot;:&quot;9:14&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2356,&quot;homeScore&quot;:84,&quot;awayScore&quot;:95,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785480&quot;,&quot;text&quot;:&quot;Ante Zizic makes layup (Jeff Green assists)&quot;,&quot;clock&quot;:&quot;8:44&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2371,&quot;homeScore&quot;:86,&quot;awayScore&quot;:95,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785485&quot;,&quot;text&quot;:&quot;Denzel Valentine makes 8-foot two point shot (Bobby Portis assists)&quot;,&quot;clock&quot;:&quot;8:29&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2404,&quot;homeScore&quot;:88,&quot;awayScore&quot;:95,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785488&quot;,&quot;text&quot;:&quot;Cristiano Felicio makes dunk (Denzel Valentine assists)&quot;,&quot;clock&quot;:&quot;7:56&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2448,&quot;homeScore&quot;:88,&quot;awayScore&quot;:97,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785497&quot;,&quot;text&quot;:&quot;Ante Zizic makes two point shot&quot;,&quot;clock&quot;:&quot;7:12&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2463,&quot;homeScore&quot;:89,&quot;awayScore&quot;:97,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785506&quot;,&quot;text&quot;:&quot;Jerian Grant makes free throw 1 of 3&quot;,&quot;clock&quot;:&quot;6:57&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2463,&quot;homeScore&quot;:90,&quot;awayScore&quot;:97,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785507&quot;,&quot;text&quot;:&quot;Jerian Grant makes free throw 2 of 3&quot;,&quot;clock&quot;:&quot;6:57&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2463,&quot;homeScore&quot;:91,&quot;awayScore&quot;:97,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785508&quot;,&quot;text&quot;:&quot;Jerian Grant makes free throw 3 of 3&quot;,&quot;clock&quot;:&quot;6:57&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2482,&quot;homeScore&quot;:91,&quot;awayScore&quot;:99,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785513&quot;,&quot;text&quot;:&quot;LeBron James makes layup&quot;,&quot;clock&quot;:&quot;6:38&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2499,&quot;homeScore&quot;:93,&quot;awayScore&quot;:99,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785514&quot;,&quot;text&quot;:&quot;Bobby Portis makes 21-foot pullup jump shot (Antonio Blakeney assists)&quot;,&quot;clock&quot;:&quot;6:21&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2532,&quot;homeScore&quot;:96,&quot;awayScore&quot;:99,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785518&quot;,&quot;text&quot;:&quot;Antonio Blakeney makes three point jumper (Denzel Valentine assists)&quot;,&quot;clock&quot;:&quot;5:48&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2627,&quot;homeScore&quot;:99,&quot;awayScore&quot;:99,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785537&quot;,&quot;text&quot;:&quot;Denzel Valentine makes 26-foot three point jumper (Bobby Portis assists)&quot;,&quot;clock&quot;:&quot;4:13&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2651,&quot;homeScore&quot;:99,&quot;awayScore&quot;:101,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785545&quot;,&quot;text&quot;:&quot;LeBron James makes 19-foot two point shot&quot;,&quot;clock&quot;:&quot;3:49&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2675,&quot;homeScore&quot;:99,&quot;awayScore&quot;:103,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785548&quot;,&quot;text&quot;:&quot;LeBron James makes two point shot&quot;,&quot;clock&quot;:&quot;3:25&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2695,&quot;homeScore&quot;:99,&quot;awayScore&quot;:105,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785553&quot;,&quot;text&quot;:&quot;Jeff Green makes alley oop dunk shot (LeBron James assists)&quot;,&quot;clock&quot;:&quot;3:05&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2717,&quot;homeScore&quot;:102,&quot;awayScore&quot;:105,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785555&quot;,&quot;text&quot;:&quot;Paul Zipser makes 23-foot three point jumper (Cameron Payne assists)&quot;,&quot;clock&quot;:&quot;2:43&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2779,&quot;homeScore&quot;:105,&quot;awayScore&quot;:105,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785565&quot;,&quot;text&quot;:&quot;Cameron Payne makes 27-foot three point jumper (Paul Zipser assists)&quot;,&quot;clock&quot;:&quot;1:41&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2793,&quot;homeScore&quot;:105,&quot;awayScore&quot;:108,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785567&quot;,&quot;text&quot;:&quot;Jordan Clarkson makes three point jumper (LeBron James assists)&quot;,&quot;clock&quot;:&quot;1:27&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2793,&quot;homeScore&quot;:105,&quot;awayScore&quot;:109,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785571&quot;,&quot;text&quot;:&quot;Jordan Clarkson makes free throw 1 of 1&quot;,&quot;clock&quot;:&quot;1:27&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2841,&quot;homeScore&quot;:105,&quot;awayScore&quot;:111,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785579&quot;,&quot;text&quot;:&quot;LeBron James makes 14-foot pullup jump shot&quot;,&quot;clock&quot;:&quot;39.0&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2854,&quot;homeScore&quot;:107,&quot;awayScore&quot;:111,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785584&quot;,&quot;text&quot;:&quot;Antonio Blakeney makes dunk (Cameron Payne assists)&quot;,&quot;clock&quot;:&quot;26.8&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2855,&quot;homeScore&quot;:107,&quot;awayScore&quot;:112,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785588&quot;,&quot;text&quot;:&quot;George Hill makes free throw 1 of 2&quot;,&quot;clock&quot;:&quot;25.5&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2855,&quot;homeScore&quot;:107,&quot;awayScore&quot;:113,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785589&quot;,&quot;text&quot;:&quot;George Hill makes free throw 2 of 2&quot;,&quot;clock&quot;:&quot;25.5&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2867,&quot;homeScore&quot;:109,&quot;awayScore&quot;:113,&quot;teamId&quot;:&quot;4&quot;,&quot;id&quot;:&quot;400975785590&quot;,&quot;text&quot;:&quot;Denzel Valentine makes driving layup&quot;,&quot;clock&quot;:&quot;13.2&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2869,&quot;homeScore&quot;:109,&quot;awayScore&quot;:114,&quot;teamId&quot;:&quot;5&quot;,&quot;id&quot;:&quot;400975785593&quot;,&quot;text&quot;:&quot;George Hill makes free throw 1 of 2&quot;,&quot;clock&quot;:&quot;11.8&quot;}," \
           "{&quot;period&quot;:4,&quot;seconds&quot;:2880,&quot;homeScore&quot;:109,&quot;awayScore&quot;:114,&quot;teamId&quot;:0,&quot;id&quot;:&quot;400975785603&quot;,&quot;text&quot;:&quot;End of the 4th Quarter&quot;,&quot;clock&quot;:&quot;0.0&quot;}]"
data-homecolor="000000" data-away-id="5" data-home-id="4" data-homeabbrev="CHI" data-awayabbrev="CLE" data-awaycolor="061642" data-mininperiod="12"
data-numperiods="4" data-behavior="game_flow" style="padding: 0px; position: relative;"><canvas class="flot-base" width="537" height="225"
style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 430px; height: 180px;"></canvas><div class="flot-text"
style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; font-size: smaller; color: rgb(84, 84, 84);">
<div class="flot-x-axis flot-x1-axis xAxis x1Axis" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; display: block;">
<div class="flot-tick-label tickLabel" style="position: absolute; max-width: none; top: 166px; left: 0px; text-align: center; width: 102px; margin-left: 0px;">1st</div>
<div class="flot-tick-label tickLabel" style="position: absolute; max-width: none; top: 166px; left: 0px; text-align: center; width: 102px; margin-left: 102px;">2nd</div>
<div class="flot-tick-label tickLabel" style="position: absolute; max-width: none; top: 166px; left: 0px; text-align: center; width: 102px; margin-left: 204px;">3rd</div>
<div class="flot-tick-label tickLabel" style="position: absolute; max-width: none; top: 166px; left: 0px; text-align: center; width: 102px; margin-left: 306px;">4th</div>
</div>
<div class="flot-y-axis flot-y1-axis yAxis y1Axis" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; display: block;">
<div class="flot-tick-label tickLabel" style="position: absolute; top: 155px; left: 413px;">0</div>
<div class="flot-tick-label tickLabel" style="position: absolute; top: 123px; left: 413px;">25</div>
<div class="flot-tick-label tickLabel" style="position: absolute; top: 91px; left: 413px;">50</div>
<div class="flot-tick-label tickLabel" style="position: absolute; top: 59px; left: 413px;">75</div>
<div class="flot-tick-label tickLabel" style="position: absolute; top: 27px; left: 413px;">100</div>
</div>
</div><canvas class="flot-overlay" width="537" height="225" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 430px; height: 180px;"></canvas>
</div>